services:
  groovyls:
    build:
      dockerfile: ./packages/examples/resources/groovy/Dockerfile
      context: ../../../..
    environment:
      - HOME_DIR=/home/gradle
      - PATH_MLC=/home/gradle/mlc
      - PATH_GLS=/home/gradle/groovy-language-server
      - PATH_GROOVY_JAR=/home/gradle/mlc/packages/examples/resources/groovy/lib
    command: [
      "bash", "-c", "npm i && npm run start:example:server:groovy"
    ]
    ports:
      - 30002:30002
    working_dir: /home/gradle/mlc
    container_name: groovyls
